// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removing_list_check_v12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removing_list_check_v12));
        
        string IMigrationMetadata.Id
        {
            get { return "202212051730379_removing_list_check_v1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
