// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class checking_FK_Complete_v10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checking_FK_Complete_v10));
        
        string IMigrationMetadata.Id
        {
            get { return "202212051728432_checking_FK_Complete_v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
